package ${req.pkg};

import com.bricks.dal.BaseEO;

#foreach( ${f} in ${req.imports()} )
import ${f};
#end
/**
 * ${req.comment}
 * 
 * Auto Generated by <code>CodeGenerator</code>
 */
public abstract class Abs${req.clazzName} extends BaseEO {
	private static final long serialVersionUID = 1L;
#foreach( ${f} in ${req.staticFields} )

	/**
	 * ${f.comment}
	 */
	public static final ${f.type} ${f.name};
#end
#foreach( ${f} in ${req.fields} )

	/**
	 * ${f.comment}
	 */
	${f.toString()}// ${f.comment}
#end
#foreach( ${f} in ${req.fields} )

	/**
	 * @return ${f.name}<br/>
	 *            ${f.comment}
	 */
	public ${f.genericStr()} ${f.getterName()}() {
		return ${f.name};
	}

	/**
	 * 设置 ${f.name}<br/>
	 *            ${f.comment}
	 * 
	 * @param ${f.name}
	 */
	public void ${f.setterName()}(${f.genericStr()} ${f.name}) {
		this.${f.name} = ${f.name};
	}
#end
}
