package ${req.pkg};

import org.springframework.stereotype.Service;

import com.bricks.dal.mybatis.MybatisDAO;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
@Service
public class ${req.clazzName}Dao extends MybatisDAO<${req.clazzName}> {}
