package ${req.pkg};

/**
 * ${table.comment}
 * 
 * Auto Generated by <code>CodeGenerator</code>
 */
public class ${req.clazzName} extends Abs${req.clazzName} {
	private static final long serialVersionUID = 1L;
}
