drop table t_proj;
create table t_proj(
	ID INTEGER  GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    PROJ_CODE VARCHAR(32),
    PROJ_NAME VARCHAR(64),
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    VERSION INTEGER
);
select * from t_proj;
INSERT INTO t_proj (PROJ_CODE, PROJ_NAME, CREATE_TIME, UPDATE_TIME, VERSION) 
 	VALUES ('test_proj_0', 'test project name 0', current_timestamp,current_timestamp,1);