package ${pkg};

import cn.codingwoo.data.dao.mybatis.MybatisDAO;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
public abstract class Abs${table.className}Dao extends MybatisDAO<${table.className}> {
	
	protected String buildStatementName(String suffix) {
		return Abs${table.className}Dao.class.getName() + "." + suffix;
	}

}
