package ${pkg};

import org.springframework.stereotype.Service;

/**
 * Auto Generated by <code>CodeGenerator</code>
 */
@Service
public class ${table.className}Dao extends Abs${table.className}Dao {

}
