package ${pkg};

/**
 * ${table.comment}
 * 
 * Auto Generated by <code>CodeGenerator</code>
 */
public class ${table.className} extends Abs${table.className} {
	private static final long serialVersionUID = 1L;
}
